const en = {
  login: {
    title: 'Sign In',
    email: 'Email Address',
    password: 'Password',
    goToRegister: 'New Member ?',
    register: 'Register',
    loginButton: 'LogIn',
    insertEmail: 'Please Insert Email Address',
    insertPassword: 'Please Insert Password',
  },
  register: {
    title: 'Register',
    email: 'Email Address',
    Name: 'Name',
    phone: 'Phone Number',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    login: 'login',
    alreadyUser: 'Already Registered ?',
    registerButton: 'Register',
    insertEmail: 'Please Insert Email Address',
    insertPassword: 'Please Insert Password',
    nameValidation: 'Name must be at least 3 characters',
    emailValidation: 'Please enter a valid email address',
    phoneValidation: 'Please enter a valid 11 digit phone number',
    passwordValidation: 'Password must be at least 5 characters',
    confirmPasswordValidation: 'Passwords must match',
  },
};

const ar = {
  login: {
    title: 'تسجيل دخول',
    email: 'البريد الالكتروني',
    password: 'كلمه المرور',
    forgetPassword: 'هل نسيت كلمه المرور الخاصه بيك',
    loginButton: 'تسجيل دخول',
    insertEmail: 'منفضلك ادخل البريد الالكتروني',
    insertPassword: 'منفضلك ادخل كلمه المرور',
    goToRegister: 'عضو جديد ؟',
    register: 'التسجيل',
  },
  register: {
    title: 'التسجيل',
    email: 'البريد الالكتروني',
    Name: 'الاسم',
    phone: 'رقم الهاتف',
    password: 'كلمه المرور',
    confirmPassword: 'تاكيد كلمه المرور',
    alreadyUser: 'هل انت عضو بلفعل',
    login: 'تسجيل الدخول',
    registerButton: 'التسجيل',
    insertEmail: 'منفضلك ادحل البريد الالكتروني',
    insertPassword: 'منفضلك ادخل كلمه المرور',
    nameValidation: 'الاسم يجب ان يتكون من 3 حروف علي الاقل',
    emailValidation: 'منفضلك ادخل بريد اللكتروني صحيح',
    phoneValidation: 'منفضلك ادخل ال11 رقم',
    passwordValidation: 'كلمه المرور يجب ان تكون اكثر من 5 حروف',
    confirmPasswordValidation: 'كلمه المرور غير مطابقه',
  },
};
export { en, ar };
